### ISSUE TITLE
Cross-platform way to measure memory?

### ISSUE THREAD

**Issue by janko** [jeremyevans/simple_orm_benchmark#1]
On Mac OS `ps -o rsz` returns 0 with an error:

```
ps: no valid keywords; valid keywords:
ps: rsz: keyword not found
```

I think I've heard somewhere that `ps -o rss` is good, that RSS is something you should measure about memory. What do you think is the best way?

**Comment by jeremyevans** [comment]
Thanks for the report. The difference between rss and rsz is:

```
        rss          The real memory (resident set) size of the process (in
                     1024 byte units).

        rsz          Alias: rssize.  Resident set size + (text size / text use
                     count).
```

So switching from `rsz` to `rss` appears to mean that `(text size / text use count)` will be ignored.  However, that looks very small in practice, so I think it's safe to ignore.  I'll commit a change shortly.

**Comment by janko** [comment]
Thanks for the investigation and the fix!
